<?php foreach ($posts as $post): ?>
    <div class="row">
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted"><?= $post->getDate() ?></h6>
                    <p class="card-text"><?= htmlspecialchars($post->getContent()) ?></p>
                    <a href="#" class="card-link">View details</a>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>